import {
  useEffect,
  useState,
} from "react";

import PageHeader from "../components/common/PageHeader";
import Card from "../components/common/Card";
import StatCard from "../components/common/StatCard";

import adminService from "../services/adminService";

export default function AdminDashboard() {
  const [
    summary,
    setSummary,
  ] = useState(null);

  const [
    loading,
    setLoading,
  ] = useState(true);

  const [
    error,
    setError,
  ] = useState("");

  useEffect(() => {
    loadDashboard();
  }, []);

  async function loadDashboard() {
    try {
      setLoading(true);
      setError("");

      const data =
        await adminService.getDashboard();

      setSummary(data);
    } catch (err) {
      console.error(
        "Failed to load admin dashboard:",
        err
      );

      if (
        err?.response?.status === 403
      ) {
        setError(
          "You do not have permission to access the administration dashboard."
        );
      } else {
        setError(
          err?.response?.data?.error ||
            err?.response?.data?.message ||
            "Failed to load administration dashboard."
        );
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <PageHeader
        eyebrow="Administration"
        title="Admin dashboard"
        lead="System-wide overview of registered users, households, appliances, electricity bills and generated bill predictions."
      />

      <div className="stack">
        {error && (
          <div
            style={styles.error}
          >
            {error}
          </div>
        )}

        {loading ? (
          <Card>
            <p className="muted">
              Loading administration dashboard...
            </p>
          </Card>
        ) : summary ? (
          <>
            <div className="grid grid-4">
              <StatCard
                label="Users"
                value={
                  summary.totalUsers ??
                  0
                }
                note="Registered system accounts"
                tone="neutral"
              />

              <StatCard
                label="Households"
                value={
                  summary.totalHouseholds ??
                  0
                }
                note="Households registered in the system"
                tone="neutral"
              />

              <StatCard
                label="Appliances"
                value={
                  summary.totalAppliances ??
                  0
                }
                note="Appliances recorded across all households"
                tone="neutral"
              />

              <StatCard
                label="Electricity bills"
                value={
                  summary.totalElectricityBills ??
                  0
                }
                note="Historical electricity bills"
                tone="neutral"
              />
            </div>

            <div className="grid grid-2">
              <StatCard
                label="Bill predictions"
                value={
                  summary.totalBillPredictions ??
                  0
                }
                note="Predictions generated by the system"
                tone="neutral"
              />

              <Card
                title="System overview"
                subtitle="Current records across the Electricity Bill Predictor"
              >
                <div
                  style={
                    styles.overviewList
                  }
                >
                  <OverviewRow
                    label="Registered users"
                    value={
                      summary.totalUsers
                    }
                  />

                  <OverviewRow
                    label="Households"
                    value={
                      summary.totalHouseholds
                    }
                  />

                  <OverviewRow
                    label="Appliances"
                    value={
                      summary.totalAppliances
                    }
                  />

                  <OverviewRow
                    label="Electricity bills"
                    value={
                      summary.totalElectricityBills
                    }
                  />

                  <OverviewRow
                    label="Bill predictions"
                    value={
                      summary.totalBillPredictions
                    }
                    last
                  />
                </div>
              </Card>
            </div>
          </>
        ) : (
          <Card>
            <p className="muted">
              No administration statistics are available.
            </p>
          </Card>
        )}
      </div>
    </>
  );
}

function OverviewRow({
  label,
  value,
  last = false,
}) {
  return (
    <div
      style={{
        ...styles.overviewRow,
        ...(last
          ? {
              borderBottom:
                "none",
            }
          : {}),
      }}
    >
      <span
        style={
          styles.overviewLabel
        }
      >
        {label}
      </span>

      <strong
        style={
          styles.overviewValue
        }
      >
        {value ?? 0}
      </strong>
    </div>
  );
}

const styles = {
  error: {
    padding: "14px 16px",
    border:
      "1px solid #e5b4b4",
    borderRadius: "10px",
    background: "#fff0f0",
    color: "#9a1f1f",
  },

  overviewList: {
    display: "flex",
    flexDirection: "column",
  },

  overviewRow: {
    display: "flex",
    justifyContent:
      "space-between",
    alignItems: "center",
    gap: "20px",
    padding: "14px 0",
    borderBottom:
      "1px solid #eee3e3",
  },

  overviewLabel: {
    color: "#765f5f",
  },

  overviewValue: {
    fontSize: "20px",
    color: "#3f1515",
  },
};